apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgresdb
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresdb
    spec:
      containers:
      - image: postgres
        name: postgres
        imagePullPolicy: Never
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgresadmin
        - name: POSTGRES_DB
          value: autonum
        ports:
        - name: pgsql
          containerPort: 5432
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-claim
      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: postgres-pv-claim
status: {}
