apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{service.name}}
  name: {{service.name}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{service.name}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{service.name}}
    spec:
      containers:
        - image: {{service.name}}
          name: {{service.name}}
          imagePullPolicy: Never
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /opt/config
              readOnly: true
            - name: db-passwords
              mountPath: /opt/secrets/db/
              readOnly: true
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: {{service.name}}-config
        - name: db-passwords
          secret:
            defaultMode: 420
            secretName: {{service.name}}-db-passwords
status: {}
